name: prerelease
on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install core dependencies
        run: npm ci --no-audit
      - name: Build the project
        run: npm run build

  bump-package-version:
    name: Bump Version
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Display package.json
        run: cat ./package.json
      - name: Determine bump type
        id: determine-bump
        run: |-
          branch_name="${{ github.event.pull_request.head.ref }}"
          echo "Source branch name detected: $branch_name"
          if [[ "$branch_name" == major/* ]]; then
            bump_type="major"
          elif [[ "$branch_name" == feature/* ]]; then
            bump_type="minor"
          elif [[ "$branch_name" == bug/* || "$branch_name" == update/* ]]; then
            bump_type="patch"
          else
            bump_type="patch" # Default fallback
          fi
          echo "bump_type=$bump_type" >> $GITHUB_OUTPUT
      - name: Bump Package Version
        uses: phips28/gh-action-bump-version@master
        with:
          tag-prefix: 'v'
          default: ${{ steps.determine-bump.outputs.bump_type }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Display updated package.json
        run: cat ./package.json
      - name: Log new tag
        run: | 
          echo "New tag: ${{ steps.determine-bump.outputs.newTag }}"