name: prerelease
on:
  push:
    branches:
      - release
jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install core dependencies
        run: npm i --no-audit

      - name: Extract tag and version
        id: extract
        run: |-
          branch_name="${{ github.event.pull_request.head.ref }}"
          echo "Source branch name detected: $branch_name"

          if [[ "$branch_name" == major/* ]]; then
             bump="major"
          elif [[ "$branch_name" == feature/* ]]; then
             bump="minor"
          elif [[ "$branch_name" == bug/* || "$branch_name" == update/* ]]; then
             bump="patch"
          else
            bump="patch" # Default fallback
          fi

          echo "bump=$bump" >> $GITHUB_OUTPUT
        
      - name: Log New Version & Tag
        run: |-
          echo "New Version: ${{ steps.extract.outputs.new_version }}"
          echo "Tag: ${{ steps.extract.outputs.tag }}"

      - name: Bump Version
        uses: phips28/gh-action-bump-version@master
        with:
          default: ${{ steps.extract.outputs.bump }} # Dynamic bump type
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}