name: release
on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.check-release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18.20.1

      - name: Get version from package.json
        id: version
        run: |
          version=$(jq -r '.version' package.json)
          echo "current_version=$version" >> $GITHUB_OUTPUT

      - uses: navikt/github-app-token-generator@v1.0.0
        id: get-token
        with:
          private-key: ${{ secrets.TOKENS_PRIVATE_KEY }}
          app-id: ${{ secrets.TOKENS_APP_ID }}

      - name: Create GitHub release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ steps.version.outputs.current_version }}
          release_name: "Release v${{ steps.version.outputs.current_version }}"
          body: "Automatically created release for version v${{ steps.version.outputs.current_version }}."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if release was created
        id: check-release
        run: |
          if [ -n "${{ steps.create-release.outputs.id }}" ]; then
            echo "release_created=true" >> $GITHUB_OUTPUT
          else
            echo "release_created=false" >> $GITHUB_OUTPUT
          fi
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    needs: create-release
    if: ${{ needs.create-release.outputs.release_created }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18.20.1
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Install core dependencies
        run: npm ci --no-audit

      - name: Build the project
        run: npm run build

      - run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}