name: release
on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: navikt/github-app-token-generator@v1.0.0
        id: get-token
        with:
          private-key: ${{ secrets.TOKENS_PRIVATE_KEY }}
          app-id: ${{ secrets.TOKENS_APP_ID }}
      - uses: GoogleCloudPlatform/release-please-action@v4
        id: release
        with:
          token: ${{ steps.get-token.outputs.token }}
          release-type: node
          package-name: react-cli

  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    needs: create-release
    if: ${{ needs.create-release.outputs.release_created }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18.20.1
          cache: npm
          registry-url: https://registry.npmjs.org/

      - name: Install core dependencies
        run: npm ci --no-audit

      - run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}